from pathlib import Path
import json, csv
from dataclasses import asdict
from .schemas import table_to_dataframe, report_summary

VISUALIZATIONS = [
 ('trace_ecology_overview.html','Trace Ecology Overview',['folder_inventory_summary','stream_record_counts','source_processing_summary']),
 ('event_density_by_stream.html','Event Density by Stream',['drive_events_by_hour','tldraw_event_density','transcript_turns_by_time_bin']),
 ('actor_activity_by_stream.html','Actor Activity by Stream',['drive_user_action_counts','document_changelog_actor_counts','tldraw_actor_summary','transcript_speaker_summary']),
 ('artifact_history_overview.html','Artifact History Overview',['artifact_history_summary']),
 ('document_change_activity.html','Document Change Activity',['document_changelog_actor_counts','document_changelog_snippets']),
 ('tldraw_concept_map_activity.html','TLDraw Concept Map Activity',['tldraw_actor_summary','tldraw_by_team_action','tldraw_text_snippets']),
 ('transcript_activity.html','Transcript Activity',['transcript_speaker_summary','transcript_turns_by_time_bin','transcript_representative_snippets']),
 ('team_case_study.html','Team Case Study',['normalized_observatory_events','transcript_representative_snippets','document_changelog_snippets','tldraw_text_snippets']),
]

def _html_table(table, limit=25):
    if not table: return '<p>No matching table was generated.</p>'
    head=''.join(f'<th>{c}</th>' for c in table.columns)
    rows=''.join('<tr>'+''.join(f'<td>{str(r.get(c,""))[:300]}</td>' for c in table.columns)+'</tr>' for r in table.rows[:limit])
    return f'<h2>{table.table_id}</h2><p>{table.description} See <code>tables/{table.table_id}.csv</code>.</p><table><thead><tr>{head}</tr></thead><tbody>{rows}</tbody></table>'

def _write_visualizations(report, out):
    viz=Path(out)/'visualizations'; viz.mkdir(parents=True,exist_ok=True); paths={}; by={t.table_id:t for t in report.tables}
    css='body{font-family:system-ui,Segoe UI,sans-serif;max-width:1180px;margin:2rem auto;padding:0 1rem;line-height:1.4}table{border-collapse:collapse;width:100%;margin:1rem 0}th,td{border:1px solid #ddd;padding:.35rem;vertical-align:top}th{background:#f1f5f9}.caveat{background:#fff7ed;border:1px solid #fed7aa;padding:1rem}code{background:#f8fafc;padding:.1rem .25rem}'
    for filename,title,tids in VISUALIZATIONS:
        parts=[f'<!doctype html><html><head><meta charset="utf-8"><title>{title}</title><style>{css}</style></head><body>',f'<h1>{title}</h1>', '<p>This standalone visualization summarizes descriptive digital traces generated by Kairn. It uses local exported CSV/JSON tables only and requires no internet access.</p>', '<div class="caveat"><strong>Caveat:</strong> These are descriptive traces, not performance scores or direct measures of cognition. Missing traces do not mean missing work.</div>']
        for tid in tids: parts.append(_html_table(by.get(tid)))
        parts.append('<p>Related CSV table names are shown above. Open them from the <code>tables/</code> folder for complete data.</p></body></html>')
        p=viz/filename; p.write_text('\n'.join(parts),encoding='utf-8'); paths[f'visualization:{filename[:-5]}']=str(p)
    return paths

def _write_inventory(report, out):
    rows=[{'table_id':t.table_id,'title':t.title,'source_stream':t.source_stream,'row_count':len(t.rows),'column_count':len(t.columns),'caveat':t.caveat or ''} for t in report.tables]
    p=Path(out)/'output_table_inventory.csv'
    with open(p,'w',newline='',encoding='utf-8') as f:
        w=csv.DictWriter(f, fieldnames=['table_id','title','source_stream','row_count','column_count','caveat']); w.writeheader(); w.writerows(rows)
    return str(p)

def _md(report):
    table_ids={t.table_id for t in report.tables}; stream_counts=next((t for t in report.tables if t.table_id=='stream_record_counts'),None); proc=next((t for t in report.tables if t.table_id=='source_processing_summary'),None)
    lines=["# Kairn Observatory Report",'',f"Project: {report.project_name or ''}",f"Created: {report.created_at}",'',"## Project/folder context",f"Root: `{report.project_root or ''}`",'',"## Source processing summary"]
    if proc:
        for r in proc.rows[:20]: lines.append(f"- {r.get('source_kind')} — {r.get('action_taken')} — records: {r.get('records_written')} — `{r.get('path')}`")
    else: lines.append('No source processing summary table was generated.')
    lines += ['',"## Trace ecology summary"]
    if stream_counts:
        for r in stream_counts.rows: lines.append(f"- {r.get('source_stream')}: available={r.get('available')}, records={r.get('records')}, primary table `{r.get('primary_table')}`")
    lines += ['',"## Eight digital exhaust types detected"]
    checks=[('Document text insertion/editing','document_changelog_overall_counts'),('Document text deletion/replacement','document_changelog_actor_counts'),('File lifecycle activity','drive_file_lifecycle_summary'),('File access/sharing/permission activity','drive_file_lifecycle_summary'),('Concept-map shape creation','tldraw_by_team_action'),('Concept-map object modification','tldraw_by_team_action'),('Concept-map text annotation/labeling','tldraw_text_snippets'),('Transcript speech act / meeting turn','transcript_overall_counts')]
    for label,tid in checks: lines.append(f"- {label}: {'detected' if tid in table_ids and next((t for t in report.tables if t.table_id==tid and t.rows),None) else 'not detected or unavailable'}")
    lines += ['',"## Key descriptives",'- Drive actions: see `tables/drive_action_counts.csv` and `tables/drive_file_lifecycle_summary.csv`.','- Document edits/deletions: see `tables/document_changelog_actor_counts.csv` and `tables/document_changelog_snippets.csv`.','- TLDraw actor/object/action summaries: see `tables/tldraw_actor_summary.csv`, `tables/tldraw_by_team_object_type.csv`, and `tables/tldraw_text_snippets.csv`.','- Transcript speaker/turn/word summaries: see `tables/transcript_speaker_summary.csv`, `tables/transcript_team_summary.csv`, and `tables/transcript_keyword_counts.csv`.','',"## Cross-stream normalized events",'`tables/normalized_observatory_events.csv` combines Drive, document, TLDraw, and transcript rows into actor-time-artifact-action records where fields are available.','',"## Visualizations",'- `visualizations/trace_ecology_overview.html`','- `visualizations/event_density_by_stream.html`','- `visualizations/actor_activity_by_stream.html`','- `visualizations/artifact_history_overview.html`','- `visualizations/document_change_activity.html`','- `visualizations/tldraw_concept_map_activity.html`','- `visualizations/transcript_activity.html`','- `visualizations/team_case_study.html`','',"## Representative snippets"]
    for s in report.snippets[:20]: lines.append(f"- {s}")
    lines += ['',"## Caveats and interpretation limits"] + [f"- {c}" for c in report.caveats]
    lines += ['- Transcript duration and timestamps may be relative to recording start rather than global project time.','- Actor/speaker names may require reconciliation across platforms.']
    return '\n'.join(lines)+'\n'

def export_observatory_report(report, out_dir, include_csv=True, include_json=True, include_markdown=True, include_chart_specs=True):
    out=Path(out_dir); (out/'tables').mkdir(parents=True,exist_ok=True); (out/'charts').mkdir(parents=True,exist_ok=True); (out/'visualizations').mkdir(parents=True,exist_ok=True); paths={}
    for t in report.tables:
        if include_csv: paths[f'table_csv:{t.table_id}']=str(out/'tables'/f'{t.table_id}.csv'); table_to_dataframe(t).to_csv(paths[f'table_csv:{t.table_id}'],index=False)
        if include_json: paths[f'table_json:{t.table_id}']=str(out/'tables'/f'{t.table_id}.json'); (out/'tables'/f'{t.table_id}.json').write_text(json.dumps(asdict(t),indent=2,default=str),encoding='utf-8')
    if include_chart_specs:
        for c in report.charts:
            p=out/'charts'/f'{c.chart_id}.json'; p.write_text(json.dumps(asdict(c),indent=2),encoding='utf-8'); paths[f'chart:{c.chart_id}']=str(p)
    paths.update(_write_visualizations(report,out))
    if include_markdown:
        p=out/'kairn_observatory_report.md'; p.write_text(_md(report),encoding='utf-8'); paths['markdown']=str(p)
    paths['inventory']=_write_inventory(report,out)
    stream_availability=[t.to_dict() for t in report.tables if t.table_id=='stream_record_counts']
    processing_summary=[t.to_dict() for t in report.tables if t.table_id=='source_processing_summary']
    p=out/'report_manifest.json'; p.write_text(json.dumps({'summary':report_summary(report),'files':paths,'warnings':report.warnings,'stream_availability':stream_availability,'processing_summary':processing_summary},indent=2),encoding='utf-8'); paths['manifest']=str(p); paths['out_dir']=str(out)
    return paths
